### ISSUE TITLE
关于词库

### ISSUE THREAD

**Issue by rankun203** [daimajia/little-bear-dictionary#1]
我想问问，你的词库，是用html解析代码从各大网页词典爬下来的吗？

**Comment by daimajia** [comment]
对的，词库本打算用星际的，但是发现质量太烂...所以自己写爬虫爬取了。

**Comment by rankun203** [comment]
星际词霸，好像就是因为词典版权的原因被叫停了呢。你要不要考虑一下就是你程序如果许许多多的人用起来了，你也投入了很多感情和劳动的时候，怎么持续的问题。你用的那个开源许可证能搞定这些不？我对这个还不是很了解。

**Comment by rankun203** [comment]
星际的确实质量不怎么好，基本格式都没有。就只有换行换行。对于我这种不求量只求质的人来说，更希望看到简洁而清晰的解释。所以就自己动手做了。

**Comment by daimajia** [comment]
版权问题只能走一步看一步了。
