### ISSUE TITLE
weibo.sdk.android.sso.demo 这个库已经不存在于 weibo_android_sdk 这个项目了

### ISSUE THREAD

**Issue by lcc-321** [daimajia/little-bear-dictionary#3]
project.properties 文件中定义的依赖库 

android.library.reference.8=../../AndroidLibrarys/weibo_android_sdk/weibo.sdk.android.sso.demo

已经不存在了 ...

而且，本来 weibo.sdk.android.sso.demo 这个也不是一个库 ...

**Comment by daimajia** [comment]
很很很抱歉这会儿才看到你的issue

我今天也发现`weibo.sdk.android.sso.demo`已经不存在了。这个原来是Weibo官方推荐的一个sso开源项目，结果那个项目做的实在是太烂了...

可以考虑把那个库删掉，去掉微博认证部分。
