### ISSUE TITLE
@integer/COLOR_GREEN 已不再存在

### ISSUE THREAD

**Issue by lcc-321** [daimajia/little-bear-dictionary#5]
res/xml/setting_preference.xml 中使用的 @integer/COLOR_GREEN 已经不再存在了，是不是可以替换为 0X00FF00 ？

不解决这个问题将无法通过编译（Eclipse 就直接报错了）

**Comment by daimajia** [comment]
因为项目发布数月了，几个依赖的库有所变化，可能需要一些调整。

**Comment by lcc-321** [comment]
嗯，还好，需要调整的东西不是很多，我在发完这个 issue 的时候已经调试 OK 了

**Comment by daimajia** [comment]
可以成功编译了么?

**Comment by lcc-321** [comment]
是啊，我改成 0X00FF00 就可以了呀

**Comment by daimajia** [comment]
我是说整个项目编译通过了么？

因为这个项目的依赖比较复杂，很多开发者总是发email责备我编译流程不够简单，但是我实在想不到更简单的了，而且像`ActionBarSherlock`，`HoloEveryWhere`这种带资源的库，没法直接编译成`jar`发布...

**Comment by daimajia** [comment]
要是你全部编译过了，说明你还蛮厉害的嘿！

**Comment by lcc-321** [comment]
是啊全部编译通过了啊，我还把所有的库的 demo 也编译了一遍， 我本来就是 Java 程序员， exlipse 或者 mvn 都很熟悉，也有好好看 Android 方面的书， 嗯，Android 上手算是很简单的了

**Comment by daimajia** [comment]
赞！！！！

Android确实挺简单的，而且第三方库也比较活跃。如果对Android开源库感兴趣可以看下我总结的开源库博文。[http://blog.zhan-dui.com/?page_id=60](http://blog.zhan-dui.com/?page_id=60) 期待以后能合作做项目，也期待你能pull request。
